---
apiVersion: v1
kind: Service
metadata:
  name: vllm-server
spec:
  selector:
    app.kubernetes.io/name: vllm
  ports:
  - name: vllmport
    protocol: TCP
    port: 8001
    targetPort: 8001
  type: ClusterIP
